create table if not exists public.nas (
    id bigint generated by default as identity primary key,
    nasname varchar(255) not null,
    username varchar(255) not null,
    password text not null,
    port_authentication integer not null,
    port_accounting integer not null,
    port_api integer not null,
    port_ssh integer not null
);